copy .so to designer on build

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -11,6 +11,19 @@ override_dh_install:
 	dh_install
 	PYTHONPATH=$$(echo debian/python3-qtpyvcp/usr/lib/python3*/dist-packages) debian/python3-qtpyvcp/usr/bin/qcompile debian/python3-qtpyvcp
 	PYTHONPATH=$$(echo debian/python3-qtpyvcp/usr/lib/python3*/dist-packages) debian/python3-qtpyvcp/usr/bin/qnative --package-root $$(echo debian/python3-qtpyvcp/usr/lib/python3*/dist-packages/qtpyvcp) --build-root debian/.qnative-build
-	install -d $$(echo debian/python3-qtpyvcp/usr/lib/python3*/dist-packages/qtpyvcp/qt_plugins/designer)
-	cp $$(echo debian/python3-qtpyvcp/usr/lib/python3*/dist-packages/qtpyvcp/native/widgets_cpp/gcode_editor/*gcodeeditorplugin*.so) $$(echo debian/python3-qtpyvcp/usr/lib/python3*/dist-packages/qtpyvcp/qt_plugins/designer/)
+	set -e; \
+	pkg_root=$$(echo debian/python3-qtpyvcp/usr/lib/python3*/dist-packages); \
+	plugin_src_dir="$$pkg_root/qtpyvcp/native/widgets_cpp/gcode_editor"; \
+	plugin_dst_dir="$$pkg_root/qtpyvcp/qt_plugins/designer"; \
+	install -d "$$plugin_dst_dir"; \
+	found=0; \
+	for so in "$$plugin_src_dir"/*gcodeeditorplugin*.so; do \
+		[ -e "$$so" ] || continue; \
+		install -m 0644 "$$so" "$$plugin_dst_dir/"; \
+		found=1; \
+	done; \
+	if [ "$$found" -ne 1 ]; then \
+		echo "ERROR: No gcodeeditorplugin .so found in $$plugin_src_dir" >&2; \
+		exit 1; \
+	fi
 	rm -rf debian/.qnative-build
